baseurl = "https://qzaidi.github.io/alhusain/"
languageCode = "en-us"
title = "Al Husain Foundation"
theme = "hugo-creative-theme"
googleAnalytics = ""

publishDir = "docs"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Al Husain Foundation"
	description = "Al Husain Elementary School - call for funding support"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Al Husain Foundation"

		[params.navigation.links]
			about     = "About"
			services  = "Facilities"
			portfolio = "Projects"
			contact   = "Fund us !!"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
    logo       = "img/logo.png"
		slogan     = "Al Husain Foundation"
		subtitle   = "Al Husain Elementary School, Depok, Indonesia"
		buttonText = "Call for Funding Support"


	# About section
	[params.about]
		headline    = "Education is our responsibility to the future generations."
		description = "Al-Husain elementary school is dedicated to develop children with skills needed to improve the welfare of the generations ahead. Our goals is to develop individuals who will proudly conduct themselves as the Prophet (SAW) did which is with integrity, dignity, honor, hard work and service to all mankind as a whole."
		buttonText  = "Get started!"


	# Service section
	[params.services]
		headline = "At a glance"

      [[params.services.list]]
        icon = "fa-university"
        title = "4 classes"
        description = "From Std I until IV"

      [[params.services.list]]
			  icon = "fa-users"
			  title = "50 students"
			  description = "and we are growing ..."

		  [[params.services.list]]
        icon = "fa-graduation-cap"
        title = "9 teachers"
        description = "Lorem Ipsum Dolor Sit Amet"

		  [[params.services.list]]
        icon = "fa-user-plus"
        title = "1 administrator"
        description = "Lorem Ipsum Dolor Sit Amet"

       [[params.services.list]]
          icon = "fa-server"
          title = "Computer Lab"
          description = "Lorem Ipsum Dolor Sit Amet"

       [[params.services.list]]
          icon = "fa-moon-o"
          title = "Mosque"
          description = "Lorem Ipsum Dolor Sit Amet"

		   [[params.services.list]]
          icon = "fa-book"
          title = "Library"
          description = "Lorem Ipsum Dolor Sit Amet"

       [[params.services.list]]
          icon = "fa-cutlery"
          title = "Canteen"
          description = "Lorem Ipsum Dolor Sit Amet"

    # Aside section
	[params.aside]
		headline = "From the students"

		[params.aside.video]
			src = "video/student1.mp4"

	# Contact section
	[params.contact]
		headline = "Contact us"
		description = "Yayasan Al-Husain, Jalan Pengasinan No. 34, Kp. Kebon Kopi, Pengasinan, Kota Depok, Pengasinan Sawangan-Depok, West Java, Postal Code, 16511, Indonesia."
		phone = "+6287889675460, +62812800027037"
    email =  "alhusain23@yandex.com"

    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

	# Contact section
	[params.fund]
		headline = "Funding"
		description = "Download link for complete Funding proposal in [Bahasa Indonesia](https://alhusain23.files.wordpress.com/2017/03/rab-al-husain.xlsx) and [English](https://alhusain23.files.wordpress.com/2017/03/budget-plan-al-husain.pdf)"

		[params.fund.bank]
      name  = "BCA (Bank Central Asia)"
      account = 8800771405 
      holder = "Yayasan Al-Husain"
      swift = "CENAIDJA"
      branch = "BCA GAPLEK"
      address = "Ruko Pondok Cabe Mutiara, Jl. Pd. Cabe Raya, Pd. Cabe Udik, Pamulang, Kota Tangerang Selatan, Banten, Postal Code 15418, Indonesia"

		[params.fund.external]
      text = "Paypal"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"
      account = "IDFCUG9DCFUMBTJ"

	#Google Maps section
	 [params.location]
	 	latitude  = "-6.4180232"
	 	longitude = "106.6827496"
	 	maps_api_key = "AIzaSyCKR5VNRgNY_Q8Wr2PK05nwG1EqlueF1ZY"
